### ISSUE TITLE
请问你获得rico数据集标注后的txt了吗？

### ISSUE THREAD

**Issue by diaoa1900** [jin1ming/gedis#1]
很抱歉，用这种方式联系你，请问你现在成功获得rico数据集标注后的txt了吗，复现Jieshan Chen的论文所述实验结果了吗？

**Comment by jin1ming** [comment]
欢迎交流，我处理后的rico训练方式和Jieshan Chen的不太一样，理论上我用的那种处理方式会比他们好一点。
你如果只需要复现Jieshan Chen的实验结果，建议使用他们的训练数据：https://github.com/MulongXie/Research-ReverselyGeneratingWebCode/tree/master/code/MODULE/rico

**Comment by diaoa1900** [comment]
![14055_box](https://user-images.githubusercontent.com/65444591/190844745-ebd60161-ad22-4e75-9c2f-63d434ad009e.jpg)
我使用了Jieshan Chen的标注文件，但是发现标注文件里存在一些错误（就像图中所示这样（使用json）），不论是.json文件还是.txt文件（txt文件能比json好一些），我之前也尝试过你的标注方式，确实非常棒，然而我需要得到xyxy坐标，将你的draw_image.py代码第57行和第58行画图修改为将xyxy添加到数组中，运行后发现有一些多余，检查后发现是数据集原始json就这样标注，感觉Button和Image重叠可能会影响目标检测结果
![14055_bbox](https://user-images.githubusercontent.com/65444591/190848805-1e40d579-40db-4cf5-9439-455343f89161.jpg)

**Comment by jin1ming** [comment]
我在训练时是当作一类进行考虑的，所以这种重叠情况不会出现。你的这种问题我建议参考[clay](https://github.com/google-research-datasets/clay)中的数据，它对这种重叠的应该做了许多处理。如果它的这种不起作用的话，可能需要自己写个去重的方法了。

**Comment by diaoa1900** [comment]
ok，我去试一试，非常感谢！

**Comment by jin1ming** [comment]
还有里面有一些图片的数据是很难修正的，建议找出uied、clay里面过滤后图片的交集，在上面进行处理和训练。
